In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4])

In [ ]:
b = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])

In [ ]:
print(b)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [ ]:
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [ ]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.random.random((2,5))

array([[0.42990337, 0.18840942, 0.98524876, 0.73880962, 0.2159471 ],
       [0.15011917, 0.86040336, 0.49300706, 0.10364582, 0.46769157]])

In [ ]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [ ]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [ ]:
#ndim gives the dimentions of array
a1.ndim

1

In [ ]:
#SHAPE
a1.shape

(10,)

In [ ]:
#size
a2.size

12

In [ ]:
#item size it gives size of item
a2.itemsize

8

In [ ]:
#dtpe
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)


int64
float64
int64


changing data type

In [ ]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

array opertations

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [ ]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
a1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [ ]:
# relational
a2 > 15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
a2 == 8

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
# vector operation
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [ ]:
a1*a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [ ]:
# numpy functions max/min/sum/prod
np.max(a1)

11

In [ ]:
np.min(a2)

12

In [ ]:
np.prod(a2)

647647525324800

In [ ]:
np.max(a1,axis = 0)

array([ 8,  9, 10, 11])

In [ ]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.max(a1,axis=1)

array([ 3,  7, 11])

In [ ]:
# statistiacal operations mean / median/ mode
np.mean(a1)


5.5

In [ ]:
np.mean(a1,axis=1)

array([1.5, 5.5, 9.5])

In [ ]:
# trignometric functions
np.sin(a1)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021]])

In [ ]:
# dor product
a2 =np.arange(12).reshape(3,4)
a3 =np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [ ]:
#log and exponants
np.log(a1)

<ipython-input-26-75eed7e82f31>:2: RuntimeWarning: divide by zero encountered in log
  np.log(a1)


array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527]])

In [ ]:
np.exp(a1)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [ ]:
#round , floor, ceil
np.round(np.random.random((2,3))*100)

array([[ 8., 77., 87.],
       [87., 75., 87.]])

In [ ]:
np.floor(np.random.random((2,3))*100)

array([[89., 36., 40.],
       [54., 30.,  2.]])

In [ ]:
np.ceil(np.random.random((2,3))*100)

array([[63., 17., 38.],
       [21., 28., 39.]])

index and slicing

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [ ]:
a1[-1]

9

In [ ]:
a2[1][2]

6

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[1,2]

6

In [ ]:
a2[2,3]

11

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3[1,0,1]

5